[build]
  publish = "build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[context.production.environment]
  REACT_APP_API_URL = "https://toshi-web-app.onrender.com/api"
  REACT_APP_WHATSAPP_PHONE = "+254713159136"

[context.deploy-preview.environment]
  REACT_APP_API_URL = "https://toshi-web-app.onrender.com/api"
  REACT_APP_WHATSAPP_PHONE = "+254713159136"
